url: 
baseurl: https://akademickyosetreno.github.io

# Site settings
title: Leni Krsová - školení o algoritmech a umělé inteligenci
email: l.krsova@gmail.com
description: "Téměř 10 let pracuji s algoritmy a umělou inteligencí a zkoumám jejich roli nejen v šíření informací. Pomůžu jim porozumět i vám."

# Team names, titles and social links
people:
- name: Leni Krsova
  pic: 1
  position: Výzkumnice a herní designérka
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lenikrsova

# Postal address (add as many lines as necessary)
address:
  - line: Praha, Česká republika
  - line: IČ 07939175

# Build settings
markdown: kramdown
permalink: pretty
