url: 
baseurl: https://akademickyosetreno.github.io

# Site settings
title: Akademicky ošetřeno: Algoritmy, sociální sítě & AI (semináře, články)
email: l.krsova@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Leni Krsova
  pic: 1
  position: Výzkumnice a herní designérka
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lenikrsova

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
