url: 
baseurl: https://akademickyosetreno.github.io

# Site settings
title: Leni Krsová - školení o algoritmech a umělé inteligenci nejen na sítích a ve hrách
email: l.krsova@gmail.com
description: "Semináře a školení o algoritmech na sociálních sítích, šíření informací, a umělé inteligenci obecně"

# Team names, titles and social links
people:
- name: Leni Krsová
  pic: 1
  position: Výzkumnice a herní designérka
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lenikrsova

# Postal address (add as many lines as necessary)
address:
  - Praha, Česká republika
  - line: IČO: 07939175

# Build settings
markdown: kramdown
permalink: pretty
